{% set name = "azure-storage-files-shares-cpp" %}
{% set version = "12.5.0" %}
{% set sha256 = "676ed3b1784ce7e6a8c83be0c10ce61c87729231f54027babe7de78c28cb2a10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Azure/azure-sdk-for-cpp/archive/refs/tags/azure-storage-files-shares_{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler("cxx") }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
  host:
    - azure-storage-common-cpp >=12.3.2
  run:
    - azure-core-cpp
    - azure-storage-common-cpp >=12.3.2

test:
  commands:
    - test -f "${PREFIX}/include/azure/storage/files/shares.hpp"  # [not win]
    - test -f "${PREFIX}/lib/libazure-storage-files-shares${SHLIB_EXT}"  # [not win]
    - test -f "${PREFIX}/share/azure-storage-files-shares-cpp/azure-storage-files-shares-cppTargets.cmake"  # [not win]
    - if not exist %PREFIX%\\Library\\bin\\azure-storage-files-shares.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\include\\azure\\storage\\files\\shares.hpp exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\azure-storage-files-shares.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\share\\azure-storage-files-shares-cpp\\azure-storage-files-shares-cppTargets.cmake exit 1  # [win]

about:
  home: https://github.com/Azure/azure-sdk-for-cpp/
  summary: Azure Storage Files Shares Client Library for C++
  description: >-
    Azure File Shares offers fully managed file shares in the cloud that are
    accessible via the industry standard Server Message Block (SMB) protocol.
    Azure file shares can be mounted concurrently by cloud or on-premises
    deployments of Windows, Linux, and macOS. Additionally, Azure file shares
    can be cached on Windows Servers with Azure File Sync for fast access near
    where the data is being used.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
    - sdk/storage/azure-storage-files-shares/NOTICE.txt
  doc_url: https://azure.github.io/azure-sdk-for-cpp/
  dev_url: https://github.com/Azure/azure-sdk-for-cpp/tree/main/sdk/storage/azure-storage-files-shares/

extra:
  recipe-maintainers:
    - jdblischak
    - Shelnutt2
