{% set name = "azure-identity-cpp" %}
{% set version = "1.5.1" %}
{% set sha256 = "651a660592540c267420b7e1c8dc98428a17396e45f7f6c92a864ab9a4fa028a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Azure/azure-sdk-for-cpp/archive/refs/tags/azure-identity_{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler("cxx") }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
  host:
    - azure-core-cpp >=1.9.0
    - openssl
  run:
    - azure-core-cpp >=1.9.0
    - openssl

about:
  home: https://github.com/Azure/azure-sdk-for-cpp/
  summary: "Azure SDK for C++: Azure Identity client library for C++"
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
    - sdk/identity/azure-identity/NOTICE.txt
  doc_url: https://azure.github.io/azure-sdk-for-cpp/
  dev_url: https://github.com/Azure/azure-sdk-for-cpp/tree/main/sdk/identity/azure-identity

extra:
  recipe-maintainers:
    - jdblischak
