{% set name = "azure-identity-cpp" %}
{% set version = "1.5.1" %}
{% set sha256 = "651a660592540c267420b7e1c8dc98428a17396e45f7f6c92a864ab9a4fa028a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Azure/azure-sdk-for-cpp/archive/refs/tags/azure-identity_{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler("cxx") }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
  host:
    - azure-core-cpp >=1.9.0
    - openssl
  run:
    - azure-core-cpp >=1.9.0
    - openssl

test:
  commands:
    - test -f "${PREFIX}/include/azure/identity.hpp"  # [not win]
    - test -f "${PREFIX}/lib/libazure-identity${SHLIB_EXT}"  # [not win]
    - test -f "${PREFIX}/share/azure-identity-cpp/azure-identity-cppTargets.cmake"  # [not win]
    - if not exist %PREFIX%\\Library\\bin\\azure-identity.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\include\\azure\\identity.hpp exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\azure-identity.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\share\\azure-identity-cpp\\azure-identity-cppTargets.cmake exit 1  # [win]

about:
  home: https://github.com/Azure/azure-sdk-for-cpp/
  summary: Azure Identity client library for C++
  description: >-
    The Azure Identity library provides Azure Active Directory token
    authentication support across the Azure SDK. It provides a set of
    `TokenCredential` implementations which can be used to construct Azure SDK
    clients which support AAD token authentication.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
    - sdk/identity/azure-identity/NOTICE.txt
  doc_url: https://azure.github.io/azure-sdk-for-cpp/
  dev_url: https://github.com/Azure/azure-sdk-for-cpp/tree/main/sdk/identity/azure-identity/

extra:
  recipe-maintainers:
    - jdblischak
    - Shelnutt2
