{% set name = "wil" %}
{% set version = "1.0.230629.1" %}
{% set sha256 = "c0d9ad1f295e181aa28d7c9b219e7d530e6bc4b7533317be50e7eae760c8d63f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/microsoft/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [not win]

requirements:
  build:
    - {{ compiler("cxx") }}
    - cmake
    - ninja

about:
  home: https://github.com/microsoft/wil
  summary: Microsoft Windows Implementation Library
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/Microsoft/wil/wiki
  dev_url: https://github.com/microsoft/wil

extra:
  recipe-maintainers:
    - jdblischak
