{% set name = "azure-core-cpp" %}
{% set version = "1.10.0" %}
{% set sha256 = "e6ae26ad30376bef6272024564764ba7bf5756063dc94cc4b74180cd004ab75e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Azure/azure-sdk-for-cpp/archive/refs/tags/azure-core_{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler("cxx") }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
  host:
    - libcurl
    - openssl  # [not win]
    - wil  # [win]
  run:
    - libcurl
    - openssl  # [not win]
    - wil  # [win]

test:
  commands:
    - test -f "${PREFIX}/include/azure/core.hpp"  # [not win]
    - test -f "${PREFIX}/lib/libazure-core.${SHLIB_EXT}"  # [not win]
    - test -f "${PREFIX}/share/azure-core-cpp/azure-core-cppTargets.cmake"  # [not win]
    - if not exist %PREFIX%\\Library\\bin\\azure-core.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\include\\azure\\core.hpp exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\azure-core.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\share\\azure-core-cpp\\azure-core-cppTargets.cmake exit 1  # [win]

about:
  home: https://github.com/Azure/azure-sdk-for-cpp/
  summary: Azure SDK Core Library for C++
  description: >-
    Azure::Core (`azure-core`) provides shared primitives, abstractions, and
    helpers for modern Azure SDK client libraries written in the C++
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
    - sdk/core/azure-core/NOTICE.txt
  doc_url: https://azure.github.io/azure-sdk-for-cpp/
  dev_url: https://github.com/Azure/azure-sdk-for-cpp/tree/main/sdk/core/azure-core/

extra:
  recipe-maintainers:
    - jdblischak
    - Shelnutt2
