{% set name = "azure-storage-queues-cpp" %}
{% set version = "12.0.0" %}
{% set sha256 = "be038bd8b83b82b79e2bbdd428b958f4662b1cc1747035af94f30c7fb1e76d08" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Azure/azure-sdk-for-cpp/archive/refs/tags/azure-storage-queues_{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler("cxx") }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
  host:
    - azure-storage-common-cpp >=12.2.3
  run:
    - azure-core-cpp
    - azure-storage-common-cpp >=12.2.3

test:
  commands:
    - test -f "${PREFIX}/include/azure/storage/queues.hpp"  # [not win]
    - test -f "${PREFIX}/lib/libazure-storage-queues${SHLIB_EXT}"  # [not win]
    - test -f "${PREFIX}/share/azure-storage-queues-cpp/azure-storage-queues-cppTargets.cmake"  # [not win]
    - if not exist %PREFIX%\\Library\\bin\\azure-storage-queues.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\include\\azure\\storage\\queues.hpp exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\azure-storage-queues.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\share\\azure-storage-queues-cpp\\azure-storage-queues-cppTargets.cmake exit 1  # [win]

about:
  home: https://github.com/Azure/azure-sdk-for-cpp/
  summary: Azure Storage Queues Client Library for C++
  description: >-
    Azure Queue storage is a service for storing large numbers of messages that
    can be accessed from anywhere in the world via authenticated calls using
    HTTP or HTTPS. A single queue message can be up to 64 KB in size, and a
    queue can contain millions of messages, up to the total capacity limit of a
    storage account.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
    - sdk/storage/azure-storage-queues/NOTICE.txt
  doc_url: https://azure.github.io/azure-sdk-for-cpp/
  dev_url: https://github.com/Azure/azure-sdk-for-cpp/tree/main/sdk/storage/azure-storage-queues/

extra:
  recipe-maintainers:
    - jdblischak
    - Shelnutt2
