{% set name = "azure-storage-files-datalake-cpp" %}
{% set version = "12.6.0" %}
{% set sha256 = "4d8d69b8f9fbe3a8faa8319f8d63e12a2b8710a784077eae4a39014dc35e30ba" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Azure/azure-sdk-for-cpp/archive/refs/tags/azure-storage-files-datalake_{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler("cxx") }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
  host:
    - azure-storage-blobs-cpp >=12.7.0
  run:
    - azure-core-cpp
    - azure-storage-common-cpp
    - azure-storage-blobs-cpp >=12.7.0

test:
  commands:
    - test -f "${PREFIX}/include/azure/storage/files/datalake/datalake_directory_client.hpp"  # [not win]
    - test -f "${PREFIX}/lib/libazure-storage-files-datalake${SHLIB_EXT}"  # [not win]
    - test -f "${PREFIX}/share/azure-storage-files-datalake-cpp/azure-storage-files-datalake-cppTargets.cmake"  # [not win]
    - if not exist %PREFIX%\\Library\\bin\\azure-storage-files-datalake.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\include\\azure\\storage\\files\\datalake\\datalake_directory_client.hpp exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\azure-storage-files-datalake.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\share\\azure-storage-files-datalake-cpp\\azure-storage-files-datalake-cppTargets.cmake exit 1  # [win]

about:
  home: https://github.com/Azure/azure-sdk-for-cpp/
  summary: Azure Storage Files Data Lake Client Library for C++
  description: >-
    Azure Data Lake includes all the capabilities required to make it easy for
    developers, data scientists, and analysts to store data of any size, shape,
    and speed, and do all types of processing and analytics across platforms and
    languages. It removes the complexities of ingesting and storing all of your
    data while making it faster to get up and running with batch, streaming, and
    interactive analytics.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
    - sdk/storage/azure-storage-files-datalake/NOTICE.txt
  doc_url: https://azure.github.io/azure-sdk-for-cpp/
  dev_url: https://github.com/Azure/azure-sdk-for-cpp/tree/main/sdk/storage/azure-storage-files-datalake/

extra:
  recipe-maintainers:
    - jdblischak
    - Shelnutt2
