{% set name = "azure-storage-blobs-cpp" %}
{% set version = "12.7.0" %}
{% set sha256 = "a28a665c740ae510053afa2c9b794052aa4de11d122b3ac4eaa0bb3bccb8983e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Azure/azure-sdk-for-cpp/archive/refs/tags/azure-storage-blobs_{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler("cxx") }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
  host:
    - azure-storage-common-cpp >=12.3.1
  run:
    - azure-core-cpp
    - azure-storage-common-cpp >=12.3.1

test:
  commands:
    - test -f "${PREFIX}/include/azure/storage/blobs/append_blob_client.hpp"  # [not win]
    - test -f "${PREFIX}/lib/libazure-storage-blobs.${SHLIB_EXT}"  # [not win]
    - test -f "${PREFIX}/share/azure-storage-blobs-cpp/azure-storage-blobs-cppTargets.cmake"  # [not win]
    - if not exist %PREFIX%\\Library\\bin\\azure-storage-blobs.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\include\\azure\\storage\\blobs\\append_blob_client.hpp exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\azure-storage-blobs.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\share\\azure-storage-blobs-cpp\\azure-storage-blobs-cppTargets.cmake exit 1  # [win]

about:
  home: https://github.com/Azure/azure-sdk-for-cpp/
  summary: Azure Storage Blobs Client Library for C++
  description: >-
    Azure Blob storage is Microsoft's object storage solution for the cloud.
    Blob storage is optimized for storing massive amounts of unstructured data.
    Unstructured data is data that does not adhere to a particular data model or
    definition, such as text or binary data.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
    - sdk/storage/azure-storage-blobs/NOTICE.txt
  doc_url: https://azure.github.io/azure-sdk-for-cpp/
  dev_url: https://github.com/Azure/azure-sdk-for-cpp/tree/main/sdk/storage/azure-storage-blobs/

extra:
  recipe-maintainers:
    - jdblischak
    - Shelnutt2
